from responses.base_response import BaseResponse
from responses.json_response import JsonResponse
from responses.text_response import TextResponse
from responses.single_word_response import SingleWordResponse
from responses.generated_questions import GeneratesQuestions
from responses.updated_description import UpdatedDescription
