# """
# Tools that helps reading the console input from the user in LINUX.
# """

# import os
# from utils.linux.mappings import Key
# if os.name != "nt":
#     key_names: dict[str, str] = {
#         Key.BEGIN: "NEW LINE",
#         Key.SHIFT_BEGIN: "SHIFT NUMERIC PAD 5",
#         Key.ALT_BEGIN: "ALT NUMERIC PAD 5",
#         Key.ALT_SHIFT_BEGIN: "ALT_SHIFT NUMERIC PAD 5",
#         Key.CTRL_BEGIN: "CTRL NUMERIC PAD 5",
#         Key.CTRL_SHIFT_BEGIN: "CTRL SHIFT NUMERIC PAD 5",
#         Key.CTRL_ALT_BEGIN: "CTRL ALT NUMERIC PAD 5",
#         Key.CTRL_ALT_SHIFT_BEGIN: "CTRL ALT SHIFT NUMERIC PAD 5",

#         Key.UP: "UP",
#         Key.SHIFT_UP: "SHIFT UP",
#         Key.ALT_UP: "ALT UP",
#         Key.ALT_SHIFT_UP: "ALT SHIFT UP",
#         Key.CTRL_UP: "CTRL UP",
#         Key.CTRL_SHIFT_UP: "CTRL SHIFT UP",
#         Key.CTRL_ALT_UP: "CTRL ALT UP",
#         Key.CTRL_ALT_SHIFT_UP: "CTRL ALT SHIFT UP",

#         Key.DOWN: "DOWN",
#         Key.SHIFT_DOWN: "SHIFT DOWN",
#         Key.ALT_DOWN: "ALT DOWN",
#         Key.ALT_SHIFT_DOWN: "ALT SHIFT DOWN",
#         Key.CTRL_DOWN: "CTRL DOWN",
#         Key.CTRL_SHIFT_DOWN: "CTRL SHIFT DOWN",
#         Key.CTRL_ALT_DOWN: "CTRL ALT DOWN",
#         Key.CTRL_ALT_SHIFT_DOWN: "CTRL ALT SHIFT DOWN",

#         Key.RIGHT: "RIGHT",
#         Key.SHIFT_RIGHT: "SHIFT RIGHT",
#         Key.ALT_RIGHT: "ALT RIGHT",
#         Key.ALT_SHIFT_RIGHT: "ALT SHIFT RIGHT",
#         Key.CTRL_RIGHT: "CTRL RIGHT",
#         Key.CTRL_SHIFT_RIGHT: "CTRL SHIFT RIGHT",
#         Key.CTRL_ALT_RIGHT: "CTRL ALT RIGHT",
#         Key.CTRL_ALT_SHIFT_RIGHT: "CTRL ALT SHIFT RIGHT",

#         Key.LEFT: "LEFT",
#         Key.SHIFT_LEFT: "SHIFT LEFT",
#         Key.ALT_LEFT: "ALT LEFT",
#         Key.ALT_SHIFT_LEFT: "ALT SHIFT LEFT",
#         Key.CTRL_LEFT: "CTRL LEFT",
#         Key.CTRL_SHIFT_LEFT: "CTRL SHIFT LEFT",
#         Key.CTRL_ALT_LEFT: "CTRL ALT LEFT",
#         Key.CTRL_ALT_SHIFT_LEFT: "CTRL ALT SHIFT LEFT",

#         Key.END: "END",
#         Key.SHIFT_END: "SHIFT END",
#         Key.ALT_END: "ALT END",
#         Key.ALT_SHIFT_END: "ALT SHIFT END",
#         Key.CTRL_END: "CTRL END",
#         Key.CTRL_SHIFT_END: "CTRL SHIFT END",
#         Key.CTRL_ALT_END: "CTRL ALT END",
#         Key.CTRL_ALT_SHIFT_END: "CTRL ALT SHIFT END",

#         Key.HOME: "HOME",
#         Key.SHIFT_HOME: "SHIFT HOME",
#         Key.ALT_HOME: "ALT HOME",
#         Key.ALT_SHIFT_HOME: "ALT SHIFT HOME",
#         Key.CTRL_HOME: "CTRL HOME",
#         Key.CTRL_SHIFT_HOME: "CTRL SHIFT HOME",
#         Key.CTRL_ALT_HOME: "CTRL ALT HOME",
#         Key.CTRL_ALT_SHIFT_HOME: "CTRL ALT SHIFT HOME",

#         Key.INSERT: "INSERT",
#         Key.SHIFT_INSERT: "SHIFT INSERT",
#         Key.ALT_INSERT: "ALT INSERT",
#         Key.ALT_SHIFT_INSERT: "ALT SHIFT INSERT",
#         Key.CTRL_INSERT: "CTRL INSERT",
#         Key.CTRL_SHIFT_INSERT: "CTRL SHIFT INSERT",
#         Key.CTRL_ALT_INSERT: "CTRL ALT INSERT",
#         Key.CTRL_ALT_SHIFT_INSERT: "CTRL ALT SHIFT INSERT",

#         Key.DEL: "DEL",
#         Key.SHIFT_DEL: "SHIFT DEL",
#         Key.ALT_DEL: "ALT DEL",
#         Key.ALT_SHIFT_DEL: "ALT SHIFT DEL",
#         Key.CTRL_DEL: "CTRL DEL",
#         Key.CTRL_SHIFT_DEL: "CTRL SHIFT DEL",
#         Key.CTRL_ALT_DEL: "CTRL ALT DEL",
#         Key.CTRL_ALT_SHIFT_DEL: "CTRL ALT SHIFT DEL",

#         Key.PG_UP: "PAGE UP",
#         Key.SHIFT_PAGE_UP: "SHIFT PAGE UP",
#         Key.ALT_PAGE_UP: "ALT UP",
#         Key.ALT_SHIFT_PAGE_UP: "ALT SHIFT PAGE UP",
#         Key.CTRL_PAGE_UP: "CTRL PAGE UP",
#         Key.CTRL_SHIFT_PAGE_UP: "CTRL SHIFT PAGE UP",
#         Key.CTRL_ALT_PAGE_UP: "CTRL ALT UP",
#         Key.CTRL_ALT_SHIFT_PAGE_UP: "CTRL ALT SHIFT PAGE UP",

#         Key.PG_DOWN: "PAGE DOWN",
#         Key.SHIFT_PAGE_DOWN: "SHIFT PAGE DOWN",
#         Key.ALT_PAGE_DOWN: "ALT PAGE DOWN",
#         Key.ALT_SHIFT_PAGE_DOWN: "ALT SHIFT PAGE DOWN",
#         Key.CTRL_PAGE_DOWN: "CTRL PAGE DOWN",
#         Key.CTRL_SHIFT_PAGE_DOWN: "CTRL SHIFT PAGE DOWN",
#         Key.CTRL_ALT_PAGE_DOWN: "CTRL ALT PAGE DOWN",
#         Key.CTRL_ALT_SHIFT_PAGE_DOWN: "CTRL ALT SHIFT PAGE DOWN",

#         Key.F1: "F1",
#         Key.SHIFT_F1: "SHIFT F1",
#         Key.ALT_F1: "ALT F1",
#         Key.ALT_SHIFT_F1: "ALT SHIFT F1",
#         Key.CTRL_F1: "CTRL F1",
#         Key.CTRL_SHIFT_F1: "CTRL SHIFT F1",
#         Key.CTRL_ALT_F1: "CTRL ALT F1",
#         Key.CTRL_ALT_SHIFT_F1: "CTRL ALT SHIFT F1",

#         Key.F2: "F2",
#         Key.SHIFT_F2: "SHIFT F2",
#         Key.ALT_F2: "ALT F2",
#         Key.ALT_SHIFT_F2: "ALT SHIFT F2",
#         Key.CTRL_F2: "CTRL F2",
#         Key.CTRL_SHIFT_F2: "CTRL SHIFT F2",
#         Key.CTRL_ALT_F2: "CTRL ALT F2",
#         Key.CTRL_ALT_SHIFT_F2: "CTRL ALT SHIFT F2",

#         Key.F3: "F3",
#         Key.SHIFT_F3: "SHIFT F3",
#         Key.ALT_F3: "ALT F3",
#         Key.ALT_SHIFT_F3: "ALT SHIFT F3",
#         Key.CTRL_F3: "CTRL F3",
#         Key.CTRL_SHIFT_F3: "CTRL SHIFT F3",
#         Key.CTRL_ALT_F3: "CTRL ALT F3",
#         Key.CTRL_ALT_SHIFT_F3: "CTRL ALT SHIFT F3",

#         Key.F4: "F4",
#         Key.SHIFT_F4: "SHIFT F4",
#         Key.ALT_F4: "ALT F4",
#         Key.ALT_SHIFT_F4: "ALT SHIFT F4",
#         Key.CTRL_F4: "CTRL F4",
#         Key.CTRL_SHIFT_F4: "CTRL SHIFT F4",
#         Key.CTRL_ALT_F4: "CTRL ALT F4",
#         Key.CTRL_ALT_SHIFT_F4: "CTRL ALT SHIFT F4",

#         Key.F5: "F5",
#         Key.SHIFT_F5: "SHIFT F5",
#         Key.ALT_F5: "ALT F5",
#         Key.ALT_SHIFT_F5: "ALT SHIFT F5",
#         Key.CTRL_F5: "CTRL F5",
#         Key.CTRL_SHIFT_F5: "CTRL SHIFT F5",
#         Key.CTRL_ALT_F5: "CTRL ALT F5",
#         Key.CTRL_ALT_SHIFT_F5: "CTRL ALT SHIFT F5",

#         Key.F6: "F6",
#         Key.SHIFT_F6: "SHIFT F6",
#         Key.ALT_F6: "ALT F6",
#         Key.ALT_SHIFT_F6: "ALT SHIFT F6",
#         Key.CTRL_F6: "CTRL F6",
#         Key.CTRL_SHIFT_F6: "CTRL SHIFT F6",
#         Key.CTRL_ALT_F6: "CTRL ALT F6",
#         Key.CTRL_ALT_SHIFT_F6: "CTRL ALT SHIFT F6",

#         Key.F7: "F7",
#         Key.SHIFT_F7: "SHIFT F7",
#         Key.ALT_F7: "ALT F7",
#         Key.ALT_SHIFT_F7: "ALT SHIFT F7",
#         Key.CTRL_F7: "CTRL F7",
#         Key.CTRL_SHIFT_F7: "CTRL SHIFT F7",
#         Key.CTRL_ALT_F7: "CTRL ALT F7",
#         Key.CTRL_ALT_SHIFT_F7: "CTRL ALT SHIFT F7",

#         Key.F8: "F8",
#         Key.SHIFT_F8: "SHIFT F8",
#         Key.ALT_F8: "ALT F8",
#         Key.ALT_SHIFT_F8: "ALT SHIFT F8",
#         Key.CTRL_F8: "CTRL F8",
#         Key.CTRL_SHIFT_F8: "CTRL SHIFT F8",
#         Key.CTRL_ALT_F8: "CTRL ALT F8",
#         Key.CTRL_ALT_SHIFT_F8: "CTRL ALT SHIFT F8",

#         Key.F9: "F9",
#         Key.SHIFT_F9: "SHIFT F9",
#         Key.ALT_F9: "ALT F9",
#         Key.ALT_SHIFT_F9: "ALT SHIFT F9",
#         Key.CTRL_F9: "CTRL F9",
#         Key.CTRL_SHIFT_F9: "CTRL SHIFT F9",
#         Key.CTRL_ALT_F9: "CTRL ALT F9",
#         Key.CTRL_ALT_SHIFT_F9: "CTRL ALT SHIFT F9",

#         Key.F10: "F10",
#         Key.SHIFT_F10: "SHIFT F10",
#         Key.ALT_F10: "ALT F10",
#         Key.ALT_SHIFT_F10: "ALT SHIFT F10",
#         Key.CTRL_F10: "CTRL F10",
#         Key.CTRL_SHIFT_F10: "CTRL SHIFT F10",
#         Key.CTRL_ALT_F10: "CTRL ALT F10",
#         Key.CTRL_ALT_SHIFT_F10: "CTRL ALT SHIFT F10",

#         Key.F11: "F11",
#         Key.SHIFT_F11: "SHIFT F11",
#         Key.ALT_F11: "ALT F11",
#         Key.ALT_SHIFT_F11: "ALT SHIFT F11",
#         Key.CTRL_F11: "CTRL F11",
#         Key.CTRL_SHIFT_F11: "CTRL SHIFT F11",
#         Key.CTRL_ALT_F11: "CTRL ALT F11",
#         Key.CTRL_ALT_SHIFT_F11: "CTRL ALT SHIFT F11",

#         Key.F12: "F12",
#         Key.SHIFT_F12: "SHIFT F12",
#         Key.ALT_F12: "ALT F12",
#         Key.ALT_SHIFT_F12: "ALT SHIFT F12",
#         Key.CTRL_F12: "CTRL F12",
#         Key.CTRL_SHIFT_F12: "CTRL SHIFT F12",
#         Key.CTRL_ALT_F12: "CTRL ALT F12",
#         Key.CTRL_ALT_SHIFT_F12: "CTRL ALT SHIFT F12",

#         Key.BACKSPACE: "BACKSPACE",
#         Key.TAB: "TAB",
#         Key.ENTER: "ENTER",
#         Key.ESC: "ESC",
#         Key.CTRL_BKSLASH: "CTRL BACKSLASH",
#         Key.CTRL_SLASH: "CTRL SLASH",
#         Key.CTRL_BACKSPACE: "CTRL BACKSPACE",
#         Key.CTRL_TAB: "CTRL TAB",
#         Key.SHIFT_TAB: "SHIFT TAB",
#         Key.CTRL_ENTER: "CTRL ENTER",
#         Key.CLEAR_LINE_AHEAD: "CLEAR_LINE_AHEAD",
#         Key.CLEAR_SCREEN_AHEAD: "CLEAR_SCREEN_AHEAD",
#         Key.CLEAR_LINE_BEHIND: "CLEAR_LINE_BEHIND",
#         Key.INS_LINE: "INS_LINE",
#         Key.DEL_LINE: "DEL_LINE",
#         Key.DEL_CHAR: "DEL_CHAR",

#         Key.CTRL_A: "CTRL A",
#         Key.CTRL_B: "CTRL B",
#         Key.CTRL_C: "CTRL C",
#         Key.CTRL_D: "CTRL D",
#         Key.CTRL_E: "CTRL E",
#         Key.CTRL_F: "CTRL F",
#         Key.CTRL_G: "CTRL G",
#         Key.CTRL_H: "CTRL BACKSPACE",
#         Key.CTRL_I: "TAB",
#         Key.CTRL_J: "CTRL ENTER",
#         Key.CTRL_K: "CTRL K",
#         Key.CTRL_L: "CTRL L",
#         Key.CTRL_M: "ENTER",
#         Key.CTRL_N: "CTRL N",
#         Key.CTRL_O: "CTRL O",
#         Key.CTRL_P: "CTRL P",
#         Key.CTRL_Q: "CTRL Q",
#         Key.CTRL_R: "CTRL R",
#         Key.CTRL_S: "CTRL S",
#         Key.CTRL_T: "CTRL T",
#         Key.CTRL_U: "CTRL U",
#         Key.CTRL_V: "CTRL V",
#         Key.CTRL_W: "CTRL W",
#         Key.CTRL_X: "CTRL X",
#         Key.CTRL_Y: "CTRL Y",
#         Key.CTRL_Z: "CTRL Z",

#         Key.CTRL_0: "CTRL 0",
#         Key.CTRL_1: "CTRL 1",
#         Key.CTRL_2: "CTRL 2",
#         Key.CTRL_3: "CTRL 3",
#         Key.CTRL_4: "CTRL 4",
#         Key.CTRL_5: "CTRL 5",
#         Key.CTRL_6: "CTRL 6",
#         Key.CTRL_7: "CTRL 7",
#         Key.CTRL_8: "CTRL 8",
#         Key.CTRL_9: "CTRL 9",
#     }
