%% @config(mermaid.json)
stateDiagram-v2
    state Planning {
        [*] --> Define_Project_Charter
        state Define_Project_Charter {
            direction LR
            [*] --> Start_Analysis
            state Start_Analysis {
                state Have_Questions <<choice>>
                [*] --> Analyse_Input: Get Input { Name, Description }
                Analyse_Input --> Update_Context: Update Context Dict
                Update_Context --> Have_Questions: Have Question?
                Have_Questions --> Human_1: Yes
                Have_Questions --> [*]: No
                Human_1 --> Analyse_Input: Answer
            }
            Start_Analysis --> Define_Scope
            state Define_Scope {
                state Approve_Scope <<choice>>
                [*] --> Analyse_Scope
                Analyse_Scope --> Update_Scope: Generate Scope
                Update_Scope --> Approve_Scope: Approved?
                Approve_Scope --> Human_2: No
                Human_2 --> Analyse_Scope: More info
                Approve_Scope --> [*]: Yes
            }
            Define_Scope --> Define_Requirements
            state Split_Requirements <<fork>>
            state Join_Requirements <<join>>
            state Define_Requirements {
                [*] --> Split_Requirements
                Split_Requirements --> Analyse_Business_Requirements: Call Business Agent
                Split_Requirements --> Analyse_System_Requirements: Call Technical Agent
                state Business_Requirements {
                    state Approve_Business_Requirements <<choice>>
                    [*] --> Analyse_Business_Requirements
                    Analyse_Business_Requirements --> Update_Business_Requirements: Generate Requirements
                    Update_Business_Requirements --> Approve_Business_Requirements: Approved?
                    Approve_Business_Requirements --> Human_3: No
                    Human_3 --> Analyse_Business_Requirements: More info
                    Approve_Business_Requirements --> Join_Requirements: Yes
                }
                state System_Requirements {
                    state Approve_System_Requirements <<choice>>
                    [*] --> Analyse_System_Requirements
                    Analyse_System_Requirements --> Update_System_Requirements: Generate Requirements
                    Update_System_Requirements --> Approve_System_Requirements: Approved?
                    Approve_System_Requirements --> Human_4: No
                    Human_4 --> Analyse_System_Requirements: More info
                    Approve_System_Requirements --> Join_Requirements: Yes
                }
                Join_Requirements --> Update_Requirements
            }
            Define_Requirements --> Define_Responsibilities
            state Define_Responsibilities {
                state Approve_Responsibilities <<choice>>
                [*] --> Analyse_Responsibilities
                Analyse_Responsibilities --> Update_Responsibilities: Generate Responsibilities
                Update_Responsibilities --> Approve_Responsibilities: Approved?
                Approve_Responsibilities --> Human_5: No
                Human_5 --> Analyse_Responsibilities: More info
                Approve_Responsibilities --> [*]: Yes
            }
        }
        Define_Project_Charter --> Define_Work
        state Define_Work {
            direction LR
            state Define_Features {
                state Approve_Features <<choice>>
                [*] --> Analyse_Features
                Analyse_Features --> Update_Features: Generate Features
                Update_Features --> Approve_Features: Approved?
                Approve_Features --> Human_6: No
                Human_6 --> Analyse_Features: More info
                Approve_Features --> [*]: Yes
            }
            Define_Features --> Define_Activities: Divide Features
            state Define_Activities {
                state Approve_Activities <<choice>>
                [*] --> Analyse_Activities
                Analyse_Activities --> Update_Activities: Generate Activities
                Update_Activities --> Approve_Activities: Approved?
                Approve_Activities --> Human_7: No
                Human_7 --> Analyse_Activities: More info
                Approve_Activities --> [*]: Yes
            }
            Define_Activities --> Define_Tasks: Divide Activities
            state Define_Tasks {
                state Approve_Tasks <<choice>>
                [*] --> Analyse_Tasks
                Analyse_Tasks --> Update_Tasks: Generate Tasks
                Update_Tasks --> Approve_Tasks: Approved?
                Approve_Tasks --> Human_8: No
                Human_8 --> Analyse_Tasks: More info
                Approve_Tasks --> [*]: Yes
            }
        }
        state Need_UI <<choice>>
        Define_Work --> Need_UI: Need UI?
        Need_UI --> Define_UI: Yes
        state Define_UI {
            state Approve_UI <<choice>>
            [*] --> Analyse_UI
            Analyse_UI --> Identify_UI_Elements
            Identify_UI_Elements --> Define_Navigation
            Define_Navigation --> Create_Wireframe
            Create_Wireframe --> Update_UI
            Update_UI --> Approve_UI: Approved?
            Approve_UI --> Human_9: No
            Human_9 --> Analyse_UI: More info
            Approve_UI --> [*]: Yes
        }
        Need_UI --> [*]: No
    }
